<a href="https://colab.research.google.com/github/shelkekunal/Practice_of_ML/blob/main/keras_hyperparameter_tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

In [ ]:
df.shape

(768, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    float64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(4), int64(5)
memory usage: 54.1 KB

In [ ]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.495990
BloodPressure               0.174469
SkinThickness               0.295138
Insulin                     0.377081
BMI                         0.315577
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [ ]:
x = df.drop('Outcome', axis=1)
y = df['Outcome']

In [ ]:
x_scaled.shape

(768, 8)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)

In [ ]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Input

In [ ]:
model = Sequential([
    Input(shape=(8,)),
    Dense(32, activation='relu'),
    Dense(1, activation = 'sigmoid')
])

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
history = model.fit(x_train_scaled, y_train,epochs=100, batch_size= 32, validation_split=0.2)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6273 - loss: 0.6648 - val_accuracy: 0.6260 - val_loss: 0.6448
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7169 - loss: 0.5605 - val_accuracy: 0.7073 - val_loss: 0.5364
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7597 - loss: 0.5012 - val_accuracy: 0.7561 - val_loss: 0.4833
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7862 - loss: 0.4687 - val_accuracy: 0.7642 - val_loss: 0.4588
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7902 - loss: 0.4519 - val_accuracy: 0.7724 - val_loss: 0.4411
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7963 - loss: 0.4399 - val_accuracy: 0.7886 - val_loss: 0.4279
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8004 - loss: 0.4309 - val_accuracy: 0.7967 - val_loss: 0.4209
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8065 - loss: 0.4241 - val_accuracy: 0.8049 - val_loss: 0.4130
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8106 - loss: 0.4182 - val_accuracy: 0.8049 - val_loss: 0.4085
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8147 - loss: 0.4136 - val_accuracy: 0.8130 - val_loss: 0.4038
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8106 - loss: 0.4090 - val_accuracy: 0.8130 - val_loss: 0.4023
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8147 - loss: 0.4051 - val_accuracy: 0.8211 - val_loss: 0.3984
Epoch 13/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8228 - loss: 0.4012 - val_accuracy: 0.8211 - val_loss: 0.3961
Epoch 14/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8228 - loss: 0.3977 - val_accuracy: 0.8211 - val_loss: 0.3919
Epoch 15/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8248 - loss: 0.3951 - val_accuracy: 0.8211 - val_loss: 0.3879
Epoch 16/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8269 - loss: 0.3914 - val_accuracy: 0.8211 - val_loss: 0.3863
Epoch 17/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8228 - loss: 0.3885 - val_accuracy: 0.8293 - val_loss: 0.3827
Epoch 18/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8248 - loss: 0.3852 - val_accuracy: 0.8293 - val_loss: 0.3804
Epoch 19/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8269 - loss: 0.3825 - val_accuracy: 0.8374 - val_loss: 0.3778
Epoch 20/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8269 - loss: 0.3799 - val_accuracy: 0.8211 - val_loss: 0.3763
Epoch 21/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8350 - loss: 0.3775 - val_accuracy: 0.8374 - val_loss: 0.3726
Epoch 22/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8330 - loss: 0.3747 - val_accuracy: 0.8374 - val_loss: 0.3695
Epoch 23/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8391 - loss: 0.3732 - val_accuracy: 0.8293 - val_loss: 0.3724
Epoch 24/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8330 - loss: 0.3703 - val_accuracy: 0.8293 - val_loss: 0.3698
Epoch 25/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8391 - loss: 0.3675 - val_accuracy: 0.8374 - val_loss: 0.3670
Epoch 26/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8391 - loss: 0.3657 - val_accuracy: 0.8374 - val_loss: 0.3639
Epoch 27/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8432 - loss: 0.3633 - val_accuracy: 0.8455 - val_loss: 0.3605
Epoch 28/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8452 - loss: 0.3612 - val_accuracy: 0.8374 - val_loss: 0.3564
Epoch 29/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8432 - loss: 0.3594 - val_accuracy: 0.8293 - val_loss: 0.3546
Epoch 30/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8452 - loss: 0.3573 - val_accuracy: 0.8374 - val_loss: 0.3548
Epoch 31/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8473 - loss: 0.3557 - val_accuracy: 0.8374 - val_loss: 0.3501
Epoch 32/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8452 - loss: 0.3540 - val_accuracy: 0.8455 - val_loss: 0.3495
Epoch 33/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8432 - loss: 0.3518 - val_accuracy: 0.8537 - val_loss: 0.3455
Epoch 34/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8432 - loss: 0.3502 - val_accuracy: 0.8537 - val_loss: 0.3432
Epoch 35/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8391 - loss: 0.3481 - val_accuracy: 0.8537 - val_loss: 0.3402
Epoch 36/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8432 - loss: 0.3464 - val_accuracy: 0.8537 - val_loss: 0.3380
Epoch 37/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8473 - loss: 0.3451 - val_accuracy: 0.8537 - val_loss: 0.3375
Epoch 38/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8513 - loss: 0.3433 - val_accuracy: 0.8537 - val_loss: 0.3357
Epoch 39/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8513 - loss: 0.3417 - val_accuracy: 0.8537 - val_loss: 0.3336
Epoch 40/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8493 - loss: 0.3406 - val_accuracy: 0.8618 - val_loss: 0.3323
Epoch 41/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8493 - loss: 0.3389 - val_accuracy: 0.8699 - val_loss: 0.3293
Epoch 42/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8473 - loss: 0.3372 - val_accuracy: 0.8618 - val_loss: 0.3299
Epoch 43/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8534 - loss: 0.3361 - val_accuracy: 0.8618 - val_loss: 0.3281
Epoch 44/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8554 - loss: 0.3343 - val_accuracy: 0.8537 - val_loss: 0.3273
Epoch 45/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8595 - loss: 0.3330 - val_accuracy: 0.8699 - val_loss: 0.3235
Epoch 46/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8574 - loss: 0.3316 - val_accuracy: 0.8699 - val_loss: 0.3219
Epoch 47/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8595 - loss: 0.3300 - val_accuracy: 0.8780 - val_loss: 0.3204
Epoch 48/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8635 - loss: 0.3294 - val_accuracy: 0.8618 - val_loss: 0.3191
Epoch 49/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8595 - loss: 0.3278 - val_accuracy: 0.8780 - val_loss: 0.3163
Epoch 50/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8595 - loss: 0.3271 - val_accuracy: 0.8780 - val_loss: 0.3141
Epoch 51/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8635 - loss: 0.3257 - val_accuracy: 0.8780 - val_loss: 0.3134
Epoch 52/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8656 - loss: 0.3244 - val_accuracy: 0.8699 - val_loss: 0.3127
Epoch 53/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3231 - val_accuracy: 0.8699 - val_loss: 0.3107
Epoch 54/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8676 - loss: 0.3221 - val_accuracy: 0.8862 - val_loss: 0.3083
Epoch 55/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8717 - loss: 0.3210 - val_accuracy: 0.8862 - val_loss: 0.3083
Epoch 56/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8717 - loss: 0.3198 - val_accuracy: 0.8780 - val_loss: 0.3065
Epoch 57/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8717 - loss: 0.3187 - val_accuracy: 0.8780 - val_loss: 0.3053
Epoch 58/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8717 - loss: 0.3178 - val_accuracy: 0.8699 - val_loss: 0.3056
Epoch 59/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8737 - loss: 0.3168 - val_accuracy: 0.8780 - val_loss: 0.3020
Epoch 60/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8737 - loss: 0.3159 - val_accuracy: 0.8699 - val_loss: 0.3032
Epoch 61/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8758 - loss: 0.3155 - val_accuracy: 0.8780 - val_loss: 0.3007
Epoch 62/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8778 - loss: 0.3143 - val_accuracy: 0.8780 - val_loss: 0.2996
Epoch 63/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8758 - loss: 0.3128 - val_accuracy: 0.8780 - val_loss: 0.3006
Epoch 64/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8758 - loss: 0.3120 - val_accuracy: 0.8699 - val_loss: 0.3002
Epoch 65/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8758 - loss: 0.3113 - val_accuracy: 0.8780 - val_loss: 0.2995
Epoch 66/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8798 - loss: 0.3108 - val_accuracy: 0.8780 - val_loss: 0.2979
Epoch 67/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8778 - loss: 0.3103 - val_accuracy: 0.8699 - val_loss: 0.2984
Epoch 68/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8758 - loss: 0.3090 - val_accuracy: 0.8699 - val_loss: 0.2963
Epoch 69/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8758 - loss: 0.3085 - val_accuracy: 0.8699 - val_loss: 0.2987
Epoch 70/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8758 - loss: 0.3078 - val_accuracy: 0.8699 - val_loss: 0.2964
Epoch 71/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8758 - loss: 0.3067 - val_accuracy: 0.8780 - val_loss: 0.2949
Epoch 72/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8758 - loss: 0.3060 - val_accuracy: 0.8699 - val_loss: 0.2946
Epoch 73/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8758 - loss: 0.3048 - val_accuracy: 0.8862 - val_loss: 0.2924
Epoch 74/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8778 - loss: 0.3042 - val_accuracy: 0.8862 - val_loss: 0.2913
Epoch 75/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8819 - loss: 0.3038 - val_accuracy: 0.8780 - val_loss: 0.2917
Epoch 76/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8778 - loss: 0.3028 - val_accuracy: 0.8780 - val_loss: 0.2896
Epoch 77/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8737 - loss: 0.3020 - val_accuracy: 0.8780 - val_loss: 0.2897
Epoch 78/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8758 - loss: 0.3013 - val_accuracy: 0.8862 - val_loss: 0.2893
Epoch 79/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8798 - loss: 0.3006 - val_accuracy: 0.8780 - val_loss: 0.2885
Epoch 80/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8819 - loss: 0.3001 - val_accuracy: 0.8699 - val_loss: 0.2880
Epoch 81/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8839 - loss: 0.2996 - val_accuracy: 0.8699 - val_loss: 0.2885
Epoch 82/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8819 - loss: 0.2987 - val_accuracy: 0.8862 - val_loss: 0.2855
Epoch 83/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8839 - loss: 0.2985 - val_accuracy: 0.8780 - val_loss: 0.2847
Epoch 84/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8819 - loss: 0.2978 - val_accuracy: 0.8780 - val_loss: 0.2846
Epoch 85/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8798 - loss: 0.2971 - val_accuracy: 0.8780 - val_loss: 0.2857
Epoch 86/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8839 - loss: 0.2965 - val_accuracy: 0.8780 - val_loss: 0.2849
Epoch 87/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8859 - loss: 0.2958 - val_accuracy: 0.8780 - val_loss: 0.2848
Epoch 88/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8839 - loss: 0.2954 - val_accuracy: 0.8780 - val_loss: 0.2829
Epoch 89/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8839 - loss: 0.2946 - val_accuracy: 0.8780 - val_loss: 0.2844
Epoch 90/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8839 - loss: 0.2941 - val_accuracy: 0.8780 - val_loss: 0.2832
Epoch 91/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8839 - loss: 0.2944 - val_accuracy: 0.8780 - val_loss: 0.2822
Epoch 92/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8839 - loss: 0.2932 - val_accuracy: 0.8780 - val_loss: 0.2824
Epoch 93/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8839 - loss: 0.2925 - val_accuracy: 0.8780 - val_loss: 0.2814
Epoch 94/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8839 - loss: 0.2919 - val_accuracy: 0.8780 - val_loss: 0.2817
Epoch 95/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8839 - loss: 0.2914 - val_accuracy: 0.8780 - val_loss: 0.2810
Epoch 96/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8839 - loss: 0.2910 - val_accuracy: 0.8780 - val_loss: 0.2806
Epoch 97/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8819 - loss: 0.2907 - val_accuracy: 0.8862 - val_loss: 0.2822
Epoch 98/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8839 - loss: 0.2898 - val_accuracy: 0.8862 - val_loss: 0.2819
Epoch 99/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8839 - loss: 0.2895 - val_accuracy: 0.8780 - val_loss: 0.2812
Epoch 100/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8839 - loss: 0.2889 - val_accuracy: 0.8862 - val_loss: 0.2790

In [ ]:
!pip install -q -U keras-tuner

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 3.7 MB/s eta 0:00:00

In [ ]:
import keras_tuner as kt

In [ ]:
def build_model(hp):
  model = Sequential()
  model.add(Input(shape=(8,))),
  model.add(Dense(32, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values=['adam', 'sgd','RMSprop','adamW'])

  model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [ ]:
tuner= kt.RandomSearch(build_model,
                       objective='val_accuracy',
                       max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [ ]:
tuner.search(x_train_scaled,y_train, epochs=5,
             validation_split=0.2,
             validation_data=(x_test,y_test))

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'sgd'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x_train_scaled, y_train, epochs=100,initial_epoch=6 , batch_size=32, validation_split=0.2)

Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.6762 - loss: 0.6274 - val_accuracy: 0.6667 - val_loss: 0.6229
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7026 - loss: 0.6075 - val_accuracy: 0.6911 - val_loss: 0.6046
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7108 - loss: 0.5911 - val_accuracy: 0.6829 - val_loss: 0.5883
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7230 - loss: 0.5765 - val_accuracy: 0.6748 - val_loss: 0.5742
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7271 - loss: 0.5640 - val_accuracy: 0.6911 - val_loss: 0.5613
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7434 - loss: 0.5530 - val_accuracy: 0.6992 - val_loss: 0.5506
Epoch 13/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7515 - loss: 0.5435 - val_accuracy: 0.6992 - val_loss: 0.5405
Epoch 14/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7515 - loss: 0.5348 - val_accuracy: 0.7073 - val_loss: 0.5314
Epoch 15/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7536 - loss: 0.5270 - val_accuracy: 0.6992 - val_loss: 0.5233
Epoch 16/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7536 - loss: 0.5199 - val_accuracy: 0.7073 - val_loss: 0.5155
Epoch 17/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7515 - loss: 0.5135 - val_accuracy: 0.7154 - val_loss: 0.5087
Epoch 18/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7495 - loss: 0.5078 - val_accuracy: 0.7236 - val_loss: 0.5022
Epoch 19/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7556 - loss: 0.5023 - val_accuracy: 0.7236 - val_loss: 0.4960
Epoch 20/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7556 - loss: 0.4973 - val_accuracy: 0.7154 - val_loss: 0.4903
Epoch 21/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7617 - loss: 0.4928 - val_accuracy: 0.7236 - val_loss: 0.4854
Epoch 22/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7658 - loss: 0.4886 - val_accuracy: 0.7236 - val_loss: 0.4804
Epoch 23/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7719 - loss: 0.4846 - val_accuracy: 0.7236 - val_loss: 0.4761
Epoch 24/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7739 - loss: 0.4811 - val_accuracy: 0.7317 - val_loss: 0.4720
Epoch 25/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7760 - loss: 0.4779 - val_accuracy: 0.7317 - val_loss: 0.4684
Epoch 26/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7862 - loss: 0.4747 - val_accuracy: 0.7317 - val_loss: 0.4644
Epoch 27/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7902 - loss: 0.4718 - val_accuracy: 0.7398 - val_loss: 0.4609
Epoch 28/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7963 - loss: 0.4690 - val_accuracy: 0.7398 - val_loss: 0.4581
Epoch 29/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7984 - loss: 0.4666 - val_accuracy: 0.7398 - val_loss: 0.4553
Epoch 30/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7984 - loss: 0.4640 - val_accuracy: 0.7398 - val_loss: 0.4523
Epoch 31/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8004 - loss: 0.4619 - val_accuracy: 0.7480 - val_loss: 0.4493
Epoch 32/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8004 - loss: 0.4597 - val_accuracy: 0.7561 - val_loss: 0.4464
Epoch 33/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8004 - loss: 0.4577 - val_accuracy: 0.7642 - val_loss: 0.4435
Epoch 34/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8004 - loss: 0.4556 - val_accuracy: 0.7642 - val_loss: 0.4413
Epoch 35/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8004 - loss: 0.4538 - val_accuracy: 0.7642 - val_loss: 0.4392
Epoch 36/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7984 - loss: 0.4520 - val_accuracy: 0.7724 - val_loss: 0.4374
Epoch 37/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8024 - loss: 0.4505 - val_accuracy: 0.7724 - val_loss: 0.4352
Epoch 38/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8004 - loss: 0.4488 - val_accuracy: 0.7642 - val_loss: 0.4335
Epoch 39/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8004 - loss: 0.4474 - val_accuracy: 0.7724 - val_loss: 0.4319
Epoch 40/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8004 - loss: 0.4461 - val_accuracy: 0.7724 - val_loss: 0.4307
Epoch 41/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8024 - loss: 0.4446 - val_accuracy: 0.7724 - val_loss: 0.4295
Epoch 42/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8004 - loss: 0.4432 - val_accuracy: 0.7724 - val_loss: 0.4279
Epoch 43/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8024 - loss: 0.4420 - val_accuracy: 0.7724 - val_loss: 0.4263
Epoch 44/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8024 - loss: 0.4407 - val_accuracy: 0.7724 - val_loss: 0.4245
Epoch 45/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8024 - loss: 0.4395 - val_accuracy: 0.7642 - val_loss: 0.4228
Epoch 46/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8004 - loss: 0.4386 - val_accuracy: 0.7724 - val_loss: 0.4215
Epoch 47/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8004 - loss: 0.4373 - val_accuracy: 0.7724 - val_loss: 0.4203
Epoch 48/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8024 - loss: 0.4363 - val_accuracy: 0.7724 - val_loss: 0.4194
Epoch 49/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.8045 - loss: 0.4352 - val_accuracy: 0.7724 - val_loss: 0.4180
Epoch 50/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.8045 - loss: 0.4343 - val_accuracy: 0.7724 - val_loss: 0.4168
Epoch 51/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.8045 - loss: 0.4332 - val_accuracy: 0.7724 - val_loss: 0.4156
Epoch 52/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8045 - loss: 0.4322 - val_accuracy: 0.7724 - val_loss: 0.4142
Epoch 53/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8045 - loss: 0.4313 - val_accuracy: 0.7724 - val_loss: 0.4131
Epoch 54/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8065 - loss: 0.4304 - val_accuracy: 0.7724 - val_loss: 0.4119
Epoch 55/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8045 - loss: 0.4295 - val_accuracy: 0.7724 - val_loss: 0.4106
Epoch 56/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.8106 - loss: 0.4287 - val_accuracy: 0.7724 - val_loss: 0.4096
Epoch 57/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8147 - loss: 0.4278 - val_accuracy: 0.7724 - val_loss: 0.4087
Epoch 58/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8106 - loss: 0.4269 - val_accuracy: 0.7724 - val_loss: 0.4079
Epoch 59/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8126 - loss: 0.4262 - val_accuracy: 0.7724 - val_loss: 0.4068
Epoch 60/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8126 - loss: 0.4253 - val_accuracy: 0.7805 - val_loss: 0.4059
Epoch 61/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8147 - loss: 0.4247 - val_accuracy: 0.7805 - val_loss: 0.4052
Epoch 62/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8126 - loss: 0.4239 - val_accuracy: 0.7805 - val_loss: 0.4046
Epoch 63/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8106 - loss: 0.4232 - val_accuracy: 0.7724 - val_loss: 0.4037
Epoch 64/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8126 - loss: 0.4224 - val_accuracy: 0.7724 - val_loss: 0.4028
Epoch 65/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8106 - loss: 0.4217 - val_accuracy: 0.7724 - val_loss: 0.4020
Epoch 66/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8106 - loss: 0.4211 - val_accuracy: 0.7724 - val_loss: 0.4014
Epoch 67/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8126 - loss: 0.4203 - val_accuracy: 0.7724 - val_loss: 0.4011
Epoch 68/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8106 - loss: 0.4196 - val_accuracy: 0.7724 - val_loss: 0.4001
Epoch 69/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8126 - loss: 0.4189 - val_accuracy: 0.7724 - val_loss: 0.3993
Epoch 70/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8126 - loss: 0.4183 - val_accuracy: 0.7724 - val_loss: 0.3986
Epoch 71/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8147 - loss: 0.4178 - val_accuracy: 0.7724 - val_loss: 0.3981
Epoch 72/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8147 - loss: 0.4172 - val_accuracy: 0.7805 - val_loss: 0.3978
Epoch 73/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8147 - loss: 0.4165 - val_accuracy: 0.7805 - val_loss: 0.3975
Epoch 74/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8126 - loss: 0.4161 - val_accuracy: 0.7886 - val_loss: 0.3965
Epoch 75/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8147 - loss: 0.4153 - val_accuracy: 0.7886 - val_loss: 0.3961
Epoch 76/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8147 - loss: 0.4147 - val_accuracy: 0.7886 - val_loss: 0.3951
Epoch 77/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8147 - loss: 0.4140 - val_accuracy: 0.7886 - val_loss: 0.3950
Epoch 78/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8126 - loss: 0.4135 - val_accuracy: 0.7886 - val_loss: 0.3940
Epoch 79/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8126 - loss: 0.4128 - val_accuracy: 0.7886 - val_loss: 0.3932
Epoch 80/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8106 - loss: 0.4123 - val_accuracy: 0.7886 - val_loss: 0.3927
Epoch 81/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8086 - loss: 0.4117 - val_accuracy: 0.7886 - val_loss: 0.3923
Epoch 82/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8086 - loss: 0.4111 - val_accuracy: 0.7886 - val_loss: 0.3912
Epoch 83/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8126 - loss: 0.4106 - val_accuracy: 0.7886 - val_loss: 0.3911
Epoch 84/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8086 - loss: 0.4100 - val_accuracy: 0.7886 - val_loss: 0.3909
Epoch 85/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8106 - loss: 0.4095 - val_accuracy: 0.7886 - val_loss: 0.3901
Epoch 86/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8086 - loss: 0.4089 - val_accuracy: 0.7967 - val_loss: 0.3900
Epoch 87/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.8086 - loss: 0.4083 - val_accuracy: 0.7967 - val_loss: 0.3895
Epoch 88/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8065 - loss: 0.4079 - val_accuracy: 0.7967 - val_loss: 0.3888
Epoch 89/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.8065 - loss: 0.4073 - val_accuracy: 0.7967 - val_loss: 0.3880
Epoch 90/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.8065 - loss: 0.4069 - val_accuracy: 0.7967 - val_loss: 0.3876
Epoch 91/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.8065 - loss: 0.4063 - val_accuracy: 0.7967 - val_loss: 0.3870
Epoch 92/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.8086 - loss: 0.4057 - val_accuracy: 0.7967 - val_loss: 0.3862
Epoch 93/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.8065 - loss: 0.4053 - val_accuracy: 0.7967 - val_loss: 0.3857
Epoch 94/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8086 - loss: 0.4047 - val_accuracy: 0.7967 - val_loss: 0.3851
Epoch 95/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8086 - loss: 0.4041 - val_accuracy: 0.7967 - val_loss: 0.3846
Epoch 96/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.8086 - loss: 0.4037 - val_accuracy: 0.7967 - val_loss: 0.3842
Epoch 97/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8045 - loss: 0.4031 - val_accuracy: 0.7967 - val_loss: 0.3838
Epoch 98/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8065 - loss: 0.4026 - val_accuracy: 0.7967 - val_loss: 0.3832
Epoch 99/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8045 - loss: 0.4022 - val_accuracy: 0.7967 - val_loss: 0.3824
Epoch 100/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8045 - loss: 0.4015 - val_accuracy: 0.7967 - val_loss: 0.3821

In [ ]:
# to find optimun no. of neurons

In [ ]:
def build_model(hp):

  model=Sequential()

  units = hp.Int('units', min_value=8, max_value=128, step=8)
  model.add(Dense(units=units, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [ ]:
tuner2 = kt.RandomSearch(build_model,
                         objective='val_accuracy',
                         max_trials=5,
                         directory = 'mydir')

In [ ]:
tuner2.search(x_train_scaled, y_train, epochs=5,
              validation_split=0.2,
              validation_data=(x_test,y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.3571428656578064

Best val_accuracy So Far: 0.4545454680919647
Total elapsed time: 00h 00m 13s

In [ ]:
tuner2.get_best_hyperparameters()[0].values

{'units': 16}